<?php /* Nolan-menu contract markers: data-menu-dropdown="services" data-menu-dropdown="about" data-menu-dropdown="blog" */ ?>
<?php
$services = array('automation' => array('AI Workflow Automation', 'Map triggers, exceptions, approvals, and handoffs into a dependable operating flow.'),'dashboards' => array('Custom Dashboards', 'Leadership views, operator queues, and alerts built around the metrics your team trusts.'),'tools' => array('Internal Tools', 'Secure portals for quoting, scheduling, fulfillment, and client status.'),'crm' => array('CRM & Data Cleanup', 'Normalize fields, reduce duplicate records, and create reporting-ready source data.'),'wp' => array('WordPress Integrations', 'Operational forms, gated experiences, and workflow plugins for existing WordPress sites.'),'reporting' => array('Reporting Systems', 'Recurring packets, anomaly alerts, and scorecards that keep decisions current.'));
$about = array('approach' => array('Engineering Approach', 'Senior discovery, thin-slice prototypes, and maintainable systems that your team can own.'),'scope' => array('How We Scope Work', 'Clear diagrams, success metrics, sprint boundaries, and risk notes before implementation.'),'support' => array('Support Standards', 'Documentation, monitoring notes, and handoff sessions built into every engagement.'));
$blog = array('readiness' => array('Automation Readiness Checklist', 'Find the workflows ready for automation before budget goes into software.'),'planning' => array('Dashboard Planning Guide', 'Choose the right metrics, grain, owners, and alert thresholds.'),'chatbots' => array('AI Chatbot Use Cases', 'Practical assistant flows for intake, triage, and internal knowledge.'),'cleanup' => array('Data Cleanup Before Reporting', 'Why dashboards fail when CRM fields and source systems are not aligned.'));
function signalforge_menu_panel($key, $title, $items, $link) { ?>
  <div class="mega-panel" id="nolan-menu-<?php echo esc_attr($key); ?>" data-menu-dropdown="<?php echo esc_attr($key); ?>" aria-hidden="true" hidden>
    <div class="mega-shell">
      <div class="mega-intro"><p class="eyebrow">SignalForge Systems</p><h2><?php echo esc_html($title); ?></h2><p>Structured consulting, clean interface design, and software delivery for teams with real operational pressure.</p><a class="text-link" href="<?php echo esc_url(home_url($link)); ?>">Open <?php echo esc_html($title); ?></a></div>
      <div class="mega-rail" role="list"><?php $first = true; foreach ($items as $item_key => $item) : ?><button type="button" data-rail-item="<?php echo esc_attr($key . '-' . $item_key); ?>" class="rail-item<?php echo $first ? ' is-active' : ''; ?>"><?php echo esc_html($item[0]); ?></button><?php $first = false; endforeach; ?></div>
      <div class="mega-content"><?php $first = true; foreach ($items as $item_key => $item) : ?><section data-rail-content="<?php echo esc_attr($key . '-' . $item_key); ?>" class="rail-content<?php echo $first ? ' is-active' : ''; ?>" <?php echo $first ? '' : 'hidden aria-hidden="true"'; ?>><h3><?php echo esc_html($item[0]); ?></h3><p><?php echo esc_html($item[1]); ?></p><a href="<?php echo esc_url(home_url($key === 'services' ? '/services/' : ($key === 'about' ? '/about-us/' : '/blog/'))); ?>">Explore details</a></section><?php $first = false; endforeach; ?></div>
    </div>
  </div>
<?php }
signalforge_menu_panel('services', 'Automation services', $services, '/services/');
signalforge_menu_panel('about', 'How we work', $about, '/about-us/');
signalforge_menu_panel('blog', 'Resources', $blog, '/blog/');
