<section class="page-hero">
	<div class="shell split">
		<div class="hero-copy">
			<p class="eyebrow">About us</p>
			<h1>Engineering discipline for teams that need dependable systems, not more noise.</h1>
			<p>AstraGrid is built for operations leaders who want clearer handoffs, stable reporting, and a support path that the team can own.</p>
			<div class="hero-actions">
				<a class="button" href="<?php echo esc_url( home_url( '/contact/' ) ); ?>">Talk to AstraGrid</a>
				<a class="button-secondary" href="<?php echo esc_url( home_url( '/services/' ) ); ?>">Review services</a>
			</div>
		</div>
		<div class="visual-panel"><img src="<?php echo esc_url( get_template_directory_uri() . '/assets/images/assistant-panel.svg' ); ?>" alt="Assistant panel"></div>
	</div>
</section>
<section class="section"><div class="shell"><div class="section-head"><p class="eyebrow">Engineering story</p><h2>We build the operating layer around the work that already exists.</h2><p class="lede">The studio exists to make operations easier to read, easier to trust, and easier to improve.</p></div><div class="grid-2"><article class="card"><h3>From process to product</h3><p>The strongest systems usually begin as a map of the way the team already works.</p></article><article class="card"><h3>Supportable by design</h3><p>Every handoff and automation includes notes, fallback logic, and owner visibility.</p></article></div></div></section>
<section class="section"><div class="shell"><div class="section-head"><p class="eyebrow">Values</p><h2>The design choices follow the operating reality.</h2><p class="lede">These principles keep the work practical for small teams that need clarity every week.</p></div><div class="grid-4"><article class="card"><h3>Data before opinion</h3><p>We map inputs, outputs, and edge cases before we shape the interface.</p></article><article class="card"><h3>Explicit handoffs</h3><p>Every automation has a visible owner, fallback, and review rule.</p></article><article class="card"><h3>Small systems, big leverage</h3><p>The best tools remove friction without adding a new platform tax.</p></article><article class="card"><h3>Supportable by the team</h3><p>If the operations team cannot maintain it, the design is not finished.</p></article></div></div></section>
<section class="section"><div class="shell band"><div class="panel split"><div><div class="section-head"><p class="eyebrow">Process</p><h2>We scope around one result at a time.</h2><p class="lede">Small, verified releases are easier to keep alive than a giant all-at-once rebuild.</p></div><div class="grid-2"><article class="card"><h3>Discovery</h3><p>We review the stack, map the route, and identify the work that repeats most often.</p></article><article class="card"><h3>Build</h3><p>We design the interface, automate the logic, and validate the reporting path.</p></article><article class="card"><h3>Handoff</h3><p>We document the system so the team can manage it without a developer on call.</p></article><article class="card"><h3>Support</h3><p>We stay available for refinements, edge cases, and new workflows.</p></article></div></div><div class="visual"><img src="<?php echo esc_url( get_template_directory_uri() . '/assets/images/orbital-data-grid.svg' ); ?>" alt="Orbital data grid"></div></div></div></section>
<section class="section"><div class="shell"><div class="section-head"><p class="eyebrow">Client experience</p><h2>The work should feel calm before and after launch.</h2><p class="lede">That means transparent milestones, predictable updates, and support rules that keep the team informed.</p></div><div class="proof-grid"><article class="proof-card"><h3>Short weekly updates</h3><p>Built for teams that need confidence during the transition.</p></article><article class="proof-card"><h3>Visible scope changes</h3><p>Built for teams that need confidence during the transition.</p></article><article class="proof-card"><h3>Support notes and fallback rules</h3><p>Built for teams that need confidence during the transition.</p></article></div></div></section>
<section class="section"><div class="shell"><div class="section-head"><p class="eyebrow">Support standards</p><h2>Maintenance is part of the product.</h2><p class="lede">The systems are documented, the owners are named, and the changes are small enough to keep current.</p></div><div class="support-grid"><article class="support-card"><h3>Named owner</h3><p>Designed so the operational layer can survive the next quarter.</p></article><article class="support-card"><h3>Documented handoff</h3><p>Designed so the operational layer can survive the next quarter.</p></article><article class="support-card"><h3>Small change windows</h3><p>Designed so the operational layer can survive the next quarter.</p></article><article class="support-card"><h3>Clean fallback path</h3><p>Designed so the operational layer can survive the next quarter.</p></article></div></div></section>
