<section class="page-hero">
	<div class="shell split">
		<div class="hero-copy">
			<p class="eyebrow">Service detail</p>
			<h1>AI Workflow Automation for teams that need fewer handoffs and cleaner queues.</h1>
			<p>We map the work, identify the repeat steps, and build a routing layer that keeps the process visible without hiding the human decisions.</p>
			<div class="hero-actions">
				<a class="button" href="<?php echo esc_url( home_url( '/contact/' ) ); ?>">Request a scope call</a>
				<a class="button-secondary" href="<?php echo esc_url( home_url( '/services/' ) ); ?>">Back to services</a>
			</div>
		</div>
		<div class="visual-panel"><img src="<?php echo esc_url( get_template_directory_uri() . '/assets/images/workflow-routing-diagram.svg' ); ?>" alt="Workflow routing diagram"></div>
	</div>
</section>
<section class="section"><div class="shell"><div class="section-head"><p class="eyebrow">Outcomes</p><h2>What this service changes for the team.</h2><p class="lede">The aim is less rework, cleaner queues, and a process the operations team can actually maintain.</p></div><div class="grid-3"><article class="service-detail"><div><h3>Fewer manual reminders</h3><p>Each automation includes a fallback path and a named owner so it can survive day-to-day use.</p></div><div class="detail-visual"><img src="<?php echo esc_url( get_template_directory_uri() . '/assets/images/automation-node-map.svg' ); ?>" alt="Automation node map"></div></article><article class="service-detail"><div><h3>Visible exception handling</h3><p>Each automation includes a fallback path and a named owner so it can survive day-to-day use.</p></div><div class="detail-visual"><img src="<?php echo esc_url( get_template_directory_uri() . '/assets/images/system-health-monitor.svg' ); ?>" alt="System health monitor"></div></article><article class="service-detail"><div><h3>Cleaner source data</h3><p>Each automation includes a fallback path and a named owner so it can survive day-to-day use.</p></div><div class="detail-visual"><img src="<?php echo esc_url( get_template_directory_uri() . '/assets/images/crm-cleanup-pipeline.svg' ); ?>" alt="CRM cleanup pipeline"></div></article></div></div></section>
<section class="section"><div class="shell"><div class="section-head"><p class="eyebrow">Delivery path</p><h2>The rollout stays short and explicit.</h2><p class="lede">A small, verified release is easier to keep healthy than a broad build with no support plan.</p></div><div class="workflow-steps"><div class="workflow-step"><span>1</span><h3>Scope the flow</h3><p>We map the steps, inputs, and exceptions that are slowing the queue.</p></div><div class="workflow-step"><span>2</span><h3>Build the routing</h3><p>We connect forms, messages, approvals, and follow-up tasks into one path.</p></div><div class="workflow-step"><span>3</span><h3>Verify the output</h3><p>We test the handoff, the fallback, and the reporting layer with real examples.</p></div><div class="workflow-step"><span>4</span><h3>Handoff support</h3><p>The team gets documentation and the owner map for the ongoing workflow.</p></div></div></div></section>
<section class="section"><div class="shell"><div class="section-head"><p class="eyebrow">Related work</p><h2>The same automation thinking shows up in dashboard and internal tool projects.</h2><p class="lede">These projects show how routing and reporting can live inside a single operational layer.</p></div><div class="grid-3"><article class="project-card"><div class="image-wrap"><img src="<?php echo esc_url( get_template_directory_uri() . '/assets/images/project-command-center.svg' ); ?>" alt="Retail operations grid"></div><div class="content"><h3>Retail operations grid</h3><p>A dispatcher workflow that reduced follow-up time by 63% across support, billing, and onboarding.</p></div></article><article class="project-card"><div class="image-wrap"><img src="<?php echo esc_url( get_template_directory_uri() . '/assets/images/reporting-dashboard.svg' ); ?>" alt="Warehouse reporting console"></div><div class="content"><h3>Warehouse reporting console</h3><p>A warehouse dashboard with live counts, issue flags, and concise shift summaries.</p></div></article><article class="project-card"><div class="image-wrap"><img src="<?php echo esc_url( get_template_directory_uri() . '/assets/images/assistant-panel.svg' ); ?>" alt="Field service intake"></div><div class="content"><h3>Field service intake</h3><p>A form-to-ticket bridge that routed jobs, notes, and images into the team queue.</p></div></article></div></div></section>
