<section class="page-hero">
	<div class="shell split">
		<div class="hero-copy">
			<p class="eyebrow">Blog</p>
			<h1>Practical guidance for automation, dashboards, and data cleanup.</h1>
			<p>These resources are written for operators, founders, and managers who need a useful answer more than a long article.</p>
			<div class="hero-actions">
				<a class="button" href="<?php echo esc_url( home_url( '/contact/' ) ); ?>">Ask about a project</a>
				<a class="button-secondary" href="<?php echo esc_url( home_url( '/services/' ) ); ?>">View services</a>
			</div>
		</div>
		<div class="visual-panel"><img src="<?php echo esc_url( get_template_directory_uri() . '/assets/images/analytics-console.svg' ); ?>" alt="Analytics console"></div>
	</div>
</section>
<section class="section"><div class="shell"><div class="section-head"><p class="eyebrow">Resource library</p><h2>A compact set of guides that help teams move faster without adding chaos.</h2><p class="lede">Each article opens with the practical question the team is trying to solve.</p></div><div class="resource-grid"><article class="resource-card"><div class="icon"><img src="<?php echo esc_url( get_template_directory_uri() . '/assets/images/automation-node-map.svg' ); ?>" alt="Automation Readiness Checklist"></div><p class="eyebrow">Article</p><h3>Automation Readiness Checklist</h3><p>A fast self-audit for identifying process bottlenecks and data gaps before building software.</p></article><article class="resource-card"><div class="icon"><img src="<?php echo esc_url( get_template_directory_uri() . '/assets/images/analytics-console.svg' ); ?>" alt="Dashboard Planning Guide"></div><p class="eyebrow">Article</p><h3>Dashboard Planning Guide</h3><p>How to choose the right metric hierarchy and avoid decorative charts that do not support decisions.</p></article><article class="resource-card"><div class="icon"><img src="<?php echo esc_url( get_template_directory_uri() . '/assets/images/assistant-panel.svg' ); ?>" alt="AI Chatbot Use Cases"></div><p class="eyebrow">Article</p><h3>AI Chatbot Use Cases</h3><p>Practical situations where AI speeds up routing, searching, and drafting without replacing governance.</p></article><article class="resource-card"><div class="icon"><img src="<?php echo esc_url( get_template_directory_uri() . '/assets/images/crm-cleanup-pipeline.svg' ); ?>" alt="Data Cleanup Before Reporting"></div><p class="eyebrow">Article</p><h3>Data Cleanup Before Reporting</h3><p>A cleanup sequence for CRM, inventory, and support data before the next board deck.</p></article><article class="resource-card"><div class="icon"><img src="<?php echo esc_url( get_template_directory_uri() . '/assets/images/terminal-card.svg' ); ?>" alt="WordPress and Back-Office Integrations"></div><p class="eyebrow">Article</p><h3>WordPress and Back-Office Integrations</h3><p>Where a website should capture structured data and where the internal system should take over.</p></article><article class="resource-card"><div class="icon"><img src="<?php echo esc_url( get_template_directory_uri() . '/assets/images/workflow-routing-diagram.svg' ); ?>" alt="The weekly operating review"></div><p class="eyebrow">Article</p><h3>The weekly operating review</h3><p>A template for running short, useful meetings with visibility into backlog, SLA drift, and exceptions.</p></article></div></div></section>
<section class="section"><div class="shell"><div class="section-head"><p class="eyebrow">Topic cards</p><h2>A quick scan of the categories we cover most often.</h2><p class="lede">These make it easy to find the right article or guide during a planning session.</p></div><div class="topic-grid"><article class="topic-card"><div class="icon"><img src="<?php echo esc_url( get_template_directory_uri() . '/assets/images/workflow-routing-diagram.svg' ); ?>" alt="Automation"></div><h3>Automation</h3><p>Reduce repetitive admin without turning the team into spreadsheet janitors.</p></article><article class="topic-card"><div class="icon"><img src="<?php echo esc_url( get_template_directory_uri() . '/assets/images/reporting-dashboard.svg' ); ?>" alt="Dashboards"></div><h3>Dashboards</h3><p>Make metrics reliable enough to drive decisions every week.</p></article><article class="topic-card"><div class="icon"><img src="<?php echo esc_url( get_template_directory_uri() . '/assets/images/crm-cleanup-pipeline.svg' ); ?>" alt="Data cleanup"></div><h3>Data cleanup</h3><p>Fix records first so automation and reporting are trustworthy later.</p></article><article class="topic-card"><div class="icon"><img src="<?php echo esc_url( get_template_directory_uri() . '/assets/images/internal-tools-interface.svg' ); ?>" alt="Internal tools"></div><h3>Internal tools</h3><p>Design compact tools around real workflows, not feature bloat.</p></article></div></div></section>
