<div class="mega-panel" id="nolan-menu-services" data-menu-dropdown="services" aria-hidden="true" hidden><div class="mega-shell"><div class="rail"><button type="button" data-rail-item="service-0" class="is-active">AI Workflow Automation</button>
      <button type="button" data-rail-item="service-1" class="">Custom Dashboards</button>
      <button type="button" data-rail-item="service-2" class="">Internal Tools</button>
      <button type="button" data-rail-item="service-3" class="">CRM & Data Cleanup</button>
      <button type="button" data-rail-item="service-4" class="">WordPress Integrations</button>
      <button type="button" data-rail-item="service-5" class="">Reporting Systems</button></div><div><section data-rail-content="service-0" class="rail-content is-active" ><h2>AI Workflow Automation</h2><p>Replace recurring handoffs with reliable routing, approvals, notifications, and assisted operations playbooks.</p><a href="<?php echo esc_url(home_url('/services/')); ?>">Explore service</a></section>
      <section data-rail-content="service-1" class="rail-content " hidden><h2>Custom Dashboards</h2><p>Give leaders a clean command view across sales, fulfillment, service, inventory, and finance signals.</p><a href="<?php echo esc_url(home_url('/services/')); ?>">Explore service</a></section>
      <section data-rail-content="service-2" class="rail-content " hidden><h2>Internal Tools</h2><p>Build focused apps for dispatch, quoting, scheduling, intake, approvals, and cross-team coordination.</p><a href="<?php echo esc_url(home_url('/services/')); ?>">Explore service</a></section>
      <section data-rail-content="service-3" class="rail-content " hidden><h2>CRM & Data Cleanup</h2><p>Normalize fields, remove duplicate records, map lifecycle stages, and prepare reporting-ready datasets.</p><a href="<?php echo esc_url(home_url('/services/')); ?>">Explore service</a></section>
      <section data-rail-content="service-4" class="rail-content " hidden><h2>WordPress Integrations</h2><p>Connect forms, memberships, content workflows, reporting endpoints, and internal review queues.</p><a href="<?php echo esc_url(home_url('/services/')); ?>">Explore service</a></section>
      <section data-rail-content="service-5" class="rail-content " hidden><h2>Reporting Systems</h2><p>Design weekly scorecards, anomaly alerts, forecasting views, and executive summaries that teams trust.</p><a href="<?php echo esc_url(home_url('/services/')); ?>">Explore service</a></section></div><aside class="mega-aside"><p class="eyebrow">Service map</p><h2>Scope the right system before anyone builds.</h2><p>We connect workflow logic, dashboards, AI support, and WordPress touchpoints into one practical roadmap.</p><a class="button" href="<?php echo esc_url(home_url('/contact/')); ?>">Book an audit</a></aside></div></div>
<div class="mega-panel" id="nolan-menu-about" data-menu-dropdown="about" aria-hidden="true" hidden><div class="mega-shell"><div class="rail"><button type="button" data-rail-item="approach" class="is-active">Engineering Approach</button><button type="button" data-rail-item="scope">How We Scope Work</button><button type="button" data-rail-item="support">Support Standards</button></div><div><section data-rail-content="approach" class="rail-content is-active"><h2>Engineering Approach</h2><p>Every engagement starts with process evidence, data ownership, and the decisions the system must support.</p><a href="<?php echo esc_url(home_url('/about-us/')); ?>">Read our approach</a></section><section data-rail-content="scope" class="rail-content" hidden><h2>How We Scope Work</h2><p>We define version-one boundaries, integrations, risks, and launch criteria before implementation begins.</p><a href="<?php echo esc_url(home_url('/about-us/')); ?>">See the process</a></section><section data-rail-content="support" class="rail-content" hidden><h2>Support Standards</h2><p>Documentation, review rhythms, and escalation paths keep internal systems useful after launch.</p><a href="<?php echo esc_url(home_url('/about-us/')); ?>">Review standards</a></section></div><aside class="mega-aside"><p class="eyebrow">Studio model</p><h2>Senior systems thinking without enterprise bloat.</h2><p>Designed for small teams that need accountable engineering and clear operating improvements.</p></aside></div></div>
<div class="mega-panel" id="nolan-menu-blog" data-menu-dropdown="blog" aria-hidden="true" hidden><div class="mega-shell"><div class="rail"><button type="button" data-rail-item="readiness" class="is-active">Automation Readiness Checklist</button><button type="button" data-rail-item="dashboards">Dashboard Planning Guide</button><button type="button" data-rail-item="chatbots">AI Chatbot Use Cases</button><button type="button" data-rail-item="cleanup">Data Cleanup Before Reporting</button></div><div><section data-rail-content="readiness" class="rail-content is-active"><h2>Automation Readiness Checklist</h2><p>Score a workflow by frequency, handoff risk, exception rate, and data quality before committing budget.</p><a href="<?php echo esc_url(home_url('/blog/')); ?>">Open resource</a></section><section data-rail-content="dashboards" class="rail-content" hidden><h2>Dashboard Planning Guide</h2><p>Choose metrics that map to decisions, owners, and operating cadence.</p><a href="<?php echo esc_url(home_url('/blog/')); ?>">Open guide</a></section><section data-rail-content="chatbots" class="rail-content" hidden><h2>AI Chatbot Use Cases</h2><p>Practical assistant patterns for intake, support, quoting, and knowledge retrieval.</p><a href="<?php echo esc_url(home_url('/blog/')); ?>">Read use cases</a></section><section data-rail-content="cleanup" class="rail-content" hidden><h2>Data Cleanup Before Reporting</h2><p>Normalize fields and lifecycle definitions before dashboards become executive fixtures.</p><a href="<?php echo esc_url(home_url('/blog/')); ?>">Read article</a></section></div><aside class="mega-aside"><p class="eyebrow">Resource library</p><h2>Make better systems decisions before the build starts.</h2><p>Guides for operators choosing automation, dashboards, and AI-assisted process changes.</p></aside></div></div>