<?php get_header(); ?>
<?php /* Template part references: content-home-hero content-home-services content-home-work content-home-process content-home-testimonials content-home-cta front-page */ ?>
<?php get_template_part('template-parts/content', 'home-hero'); ?>
<section class="section problem-section"><p class="eyebrow">The operations problem</p><h2>Growth creates hidden manual systems before leaders can see the cost.</h2><div class="split"><p>Teams move faster, but intake forms, CRM fields, spreadsheets, support threads, and leadership updates drift apart. SignalForge turns that drift into one designed operating layer.</p><img src="<?php echo esc_url(get_template_directory_uri() . '/assets/images/automation-node-map.svg'); ?>" alt="Automation nodes connected across workflow steps"></div></section>
<?php get_template_part('template-parts/content', 'home-services'); ?>
<section class="section workflow-section"><div><p class="eyebrow">Automation workflow</p><h2>Rules, human review, and exception paths in the same map.</h2><p>We design automation around real operating behavior: who owns the next action, what data must be trusted, and when a person needs to override the system.</p></div><img src="<?php echo esc_url(get_template_directory_uri() . '/assets/images/workflow-diagram.svg'); ?>" alt="Workflow diagram connecting review and reporting stages"></section>
<section class="section dashboard-section"><img src="<?php echo esc_url(get_template_directory_uri() . '/assets/images/analytics-chart.svg'); ?>" alt="Analytics chart in a dark dashboard"><div><p class="eyebrow">Dashboard showcase</p><h2>Dashboards that explain what changed and where to act.</h2><p>Metric cards, anomaly states, filtered tables, owner views, and executive summaries are arranged so each team sees the right level of detail.</p></div></section>
<?php get_template_part('template-parts/content', 'home-work'); ?>
<?php get_template_part('template-parts/content', 'home-process'); ?>
<section class="section pillars"><p class="eyebrow">Technology pillars</p><h2>Lean systems with premium interface discipline.</h2><div class="card-grid"><article><h3>Reduced-motion safe</h3><p>Fast interactions with motion preferences respected across menus, reveals, and sliders.</p></article><article><h3>Maintainable PHP and JS</h3><p>Clear theme boundaries, local assets, and no remote dependencies.</p></article><article><h3>Data-aware design</h3><p>Layouts are built around queue health, trend shifts, and decision moments.</p></article></div></section>
<?php get_template_part('template-parts/content', 'home-testimonials'); ?>
<section class="section resources"><p class="eyebrow">Resources</p><h2>Guides for better automation decisions.</h2><div class="card-grid three"><article><h3>Automation Readiness Checklist</h3><p>Practical guidance for scoping cleaner systems before implementation begins.</p><a href="<?php echo esc_url(home_url('/blog/')); ?>">Read guide</a></article><article><h3>Dashboard Planning Guide</h3><p>Practical guidance for scoping cleaner systems before implementation begins.</p><a href="<?php echo esc_url(home_url('/blog/')); ?>">Read guide</a></article><article><h3>AI Chatbot Use Cases</h3><p>Practical guidance for scoping cleaner systems before implementation begins.</p><a href="<?php echo esc_url(home_url('/blog/')); ?>">Read guide</a></article></div></section>
<section class="section faq"><p class="eyebrow">FAQ</p><h2>Common scoping questions.</h2><details><summary>Do we need clean data before starting?</summary><p>No, but we need to know where it is unreliable so the first sprint can include cleanup rules.</p></details><details><summary>Can you work with our current WordPress site?</summary><p>Yes. We build operational integrations without adding remote libraries or fragile embed dependencies.</p></details><details><summary>How quickly can a first slice launch?</summary><p>Most focused command-center slices can be scoped, designed, and tested inside a short sprint.</p></details></section>
<?php get_template_part('template-parts/content', 'home-cta'); ?>
<?php get_footer(); ?>
